### ISSUE TITLE
not loading

### ISSUE THREAD

**Issue by valeranedov** [vpodaruev/yt-cut#2]
https://www.youtube.com/live/YsKo2am5w-I?feature=share
![Снимок](https://user-images.githubusercontent.com/127602048/224484263-e76f5ba8-cc63-4fa2-8ae2-d1bae8116c38.PNG)
https://youtu.be/l1A3Q2FNKb8
![Снимок1](https://user-images.githubusercontent.com/127602048/224484286-ccd43c6f-69de-45fc-bd2b-13d1607eae59.PNG)

**Comment by vpodaruev** [comment]
The problem is on the third party side. You just need to update the `yt-dlp` executable in `tools` folder. Download the latest version [here](https://github.com/yt-dlp/yt-dlp/releases/download/2023.03.04/yt-dlp.exe).
